package com.me.isoRPG;

import com.badlogic.gdx.Game;

public class mainRPG extends Game {

	@Override
	public void create() {
		// TODO Auto-generated method stub
		setScreen(new AutogeneratedScreen(this));

	}

}
